# Generated by Django 2.0.2 on 2018-03-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YeeBT', '0002_auto_20180314_1401'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device',
            new_name='BTDevice',
        ),
    ]
