# Generated by Django 2.0.2 on 2018-03-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YeeBT', '0003_auto_20180314_1449'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BTDevice',
            new_name='YeeBTDevice',
        ),
    ]
