# Generated by Django 2.0.3 on 2018-03-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XiaomiBTDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('mac', models.CharField(max_length=17, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='XiaomiBTSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200, unique=True)),
                ('iface', models.CharField(max_length=17, unique=True)),
                ('threshold', models.CharField(max_length=17, unique=True)),
            ],
        ),
    ]
