# Generated by Django 2.0.3 on 2018-03-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_miremotecommand_miremotedevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miremotedevice',
            name='dev_ID',
        ),
        migrations.AddField(
            model_name='miremotedevice',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='miremotedevice',
            name='token',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
