# Generated by Django 2.0.3 on 2018-03-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180328_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiaomibtsetting',
            name='iface',
            field=models.CharField(max_length=17),
        ),
    ]
