# Generated by Django 2.0.1 on 2018-01-30 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=15)),
                ('token', models.CharField(max_length=200)),
                ('dev_ID', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiRemote.Device'),
        ),
    ]
