# Generated by Django 2.0.2 on 2018-02-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiRemote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='device',
        ),
    ]
