# Generated by Django 2.0.2 on 2018-02-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiRemote', '0002_remove_command_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.AlterField(
            model_name='command',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='dev_ID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
