# Generated by Django 2.0.2 on 2018-03-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiRemote', '0003_auto_20180222_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='code',
            field=models.CharField(max_length=2000),
        ),
    ]
